name: Tourism-Pipeline

on:
  push:
    branches:
      - main

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r tourism_project/requirements.txt
      - env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism_project/model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r tourism_project/requirements.txt
      - env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism_project/model_building/prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r tourism_project/requirements.txt
      - env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          FAST_CI: "true"
        run: python tourism_project/model_building/train.py

  deploy-space:
    needs: model-training
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pip install huggingface_hub

      - name: Prepare files
        run: |
          mkdir deploy_space
          cp tourism_project/deployment/app.py deploy_space/
          cp tourism_project/deployment/requirements.txt deploy_space/
          cp tourism_project/deployment/Dockerfile deploy_space/

      - name: Create README
        run: |
          echo "---" > deploy_space/README.md
          echo "title: Tourism Package Prediction" >> deploy_space/README.md
          echo "emoji: 🌍" >> deploy_space/README.md
          echo "colorFrom: blue" >> deploy_space/README.md
          echo "colorTo: green" >> deploy_space/README.md
          echo "sdk: docker" >> deploy_space/README.md
          echo "sdk_version: \"0.0.1\"" >> deploy_space/README.md
          echo "app_file: app.py" >> deploy_space/README.md
          echo "pinned: false" >> deploy_space/README.md
          echo "---" >> deploy_space/README.md

      - name: Deploy to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
from huggingface_hub import HfApi, create_repo
from huggingface_hub.utils import RepositoryNotFoundError
import os

repo_id = 'SandeepGS/tourism_package-prediction'
api = HfApi(token=os.getenv('HF_TOKEN'))

try:
    api.repo_info(repo_id=repo_id, repo_type='space')
except RepositoryNotFoundError:
    create_repo(repo_id=repo_id, repo_type='space', space_sdk='docker')

api.upload_folder('deploy_space', repo_id=repo_id, repo_type='space')
print('✅ Deployment complete')
"
